export const POST_DOG = 'POST_DOG';
export const POST_USER = 'POST_USER';
export const GET_CLOUDINARY_RESPONSE = 'GET_CLOUDINARY_RESPONSE';
export const CLEAR_CLOUDINARY_RESPONSE = 'CLEAR_CLOUDINARY_RESPONSE';
export const REMOVE_CLOUDINARY_IMAGE = 'REMOVE_CLOUDINARY_IMAGE';